// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX-oZqtDy__vkzjcR8tnwQaTrU4v9Je4E',
    appId: '1:567098115725:web:283c3d6f9b4578b8fd84c4',
    messagingSenderId: '567098115725',
    projectId: 'flutterfb-26ec9',
    authDomain: 'flutterfb-26ec9.firebaseapp.com',
    storageBucket: 'flutterfb-26ec9.firebasestorage.app',
    measurementId: 'G-W5Y2WPTWRF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2lSjFkO4oIqG56SJsiUxcn86SSCjazao',
    appId: '1:567098115725:android:035139a9539474e1fd84c4',
    messagingSenderId: '567098115725',
    projectId: 'flutterfb-26ec9',
    storageBucket: 'flutterfb-26ec9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_bjS5KoDyVnd5pLJj-gPtfSGC-9LiRMw',
    appId: '1:567098115725:ios:cffbfb85dbb9d240fd84c4',
    messagingSenderId: '567098115725',
    projectId: 'flutterfb-26ec9',
    storageBucket: 'flutterfb-26ec9.firebasestorage.app',
    iosBundleId: 'com.example.holaMundo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_bjS5KoDyVnd5pLJj-gPtfSGC-9LiRMw',
    appId: '1:567098115725:ios:cffbfb85dbb9d240fd84c4',
    messagingSenderId: '567098115725',
    projectId: 'flutterfb-26ec9',
    storageBucket: 'flutterfb-26ec9.firebasestorage.app',
    iosBundleId: 'com.example.holaMundo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX-oZqtDy__vkzjcR8tnwQaTrU4v9Je4E',
    appId: '1:567098115725:web:eb6b44329d7ed4f5fd84c4',
    messagingSenderId: '567098115725',
    projectId: 'flutterfb-26ec9',
    authDomain: 'flutterfb-26ec9.firebaseapp.com',
    storageBucket: 'flutterfb-26ec9.firebasestorage.app',
    measurementId: 'G-KYX27FH5LG',
  );

}